### ISSUE TITLE
.NET Core 2.0 Preview 2 is being rolled out to App Service

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements#14]
The rollout is expected to complete by Friday June 30th.

See [this post](https://blogs.msdn.microsoft.com/webdev/2017/06/28/introducing-asp-net-core-2-0-preview-2/) for more info about this Core release.

**Comment by davidebbo** [comment]
Some issues have been found during the deployment, and investigation is ongoing. This will delay the release. At this point, we do not have a clear ETA.

**Comment by mhobl** [comment]
Is it possible, that this rollout is producing problems on live systems?
Yesterday our site went down and after hours we found out that it has something to do with the AppServicePlan. We created a new AppServicePlan and reassigned our WebApps, which solved the problem (we have been using this plan since November 2016).
Furthermore today our site is very slow (we use the same plan setting as before) and requests are killed resulting in CGI errors. If I check the live metrics of AppInsights, it looks like some instances of the AppServicePlan are not used, although we set it to a fixed number of instances.

**Comment by mrlund** [comment]
@davidebbo Any update on this rollout? I can't seem to deploy my 2.0 site anywhere.

**Comment by davidebbo** [comment]
@mhlobil that sounds unrelated, especially since update didn't get very far and you probably don't have it.

@mrlund please see my previous comment.

Please use https://github.com/Azure/app-service-announcements-discussions/issues/2 for further discussions so we can keep this one focused on announcements/updates.

**Comment by suwatch** [comment]
The rollout is now completed.
