### ISSUE TITLE
PHP Minor Version Update for January 2019

### ISSUE THREAD

**Issue by yiliaomsft** [Azure/app-service-announcements#153]
https://blogs.msdn.microsoft.com/appserviceteam/2019/01/11/php-minor-version-update-for-january-2019/

**Comment by arzanardi** [comment]
Hello, when this version will be released?
The recent update of the latest version (5.6.38) caused me a big problem, because coincidentally (or not) in this update, for some reason made the Azure platform no longer recognize the PHP_EXTENSIONS parameter and had to implement an alternative with PHP_INI_SCAN_DIR.
Will this update impact any such changes on the platform?

There is some way to test this version before the changes in Azure?

Thanks

**Comment by sweigand** [comment]
Any update when this update will be applied?
