### ISSUE TITLE
New version 2.0.11651-alpha of the Functions runtime

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements#94]
A new version of the 2.0 Preview runtime is being deployed. Note that it has some breaking changes from the previous Preview build.

Please see https://github.com/Azure/azure-functions-host/releases/tag/v2.0.11651-alpha for details.

**Comment by davidebbo** [comment]
Please use https://github.com/Azure/app-service-announcements-discussions/issues/41 to discuss.

**Comment by paulbatum** [comment]
**This preview release introduced some breaking changes!**

You will need to update your binding extensions to resolve these breaking changes. Different workflows are required depending on how your functions are written: 
- in Visual Studio 
- through the portal
- locally using the azure-functions-core-tools (this also includes VS Code users)

### What Nuget packages do I need?

Whatever nuget references you already have will need to be updated. Use this table as a reference:

|NuGet Package | Version |
| --- | --- |
|Microsoft.NET.Sdk.Functions | 1.0.11 |
|Microsoft.Azure.WebJobs.Extensions.CosmosDB | 3.0.0-beta7|
|Microsoft.Azure.WebJobs.Extensions.* (EVERYTHING ELSE) | 3.0.0-beta5|

Please note that updates are still coming for:
`Microsoft.Azure.WebJobs.Extensions.DurableTask`
`Microsoft.Azure.WebJobs.Extensions.MicrosoftGraph`


### To fix a function app written in VS

This is basically just a NuGet update. Because you'll need to update multiple packages in one go, the easiest way to do this is to edit the .csproj file for your function app and update the references accordingly. Doing a build will then be enough to trigger a package restore. You'll then need to deploy the change. 

### To fix a function app written locally using azure-functions-core-tools (including VS Code)

1. Edit extensions.csproj 
2. Update with the appropriate versions (see above)
3. Run `func extensions sync`
4. Deploy to azure

### To fix a function app written in the Portal

Follow these steps:
1. Stop the function app.
2. Access kudu console through Platform Features -> Advanced Tools -> Debug Console (cmd)
3. Navigate to d:\home\site\wwwroot
4. Delete the bin directory
5. Edit extensions.csproj
6. Update with the appropriate versions (see above)
7. Run `dotnet publish extensions.csproj -o bin`
8. Start the function app

As a reminder, you can discuss issues/problems here:
https://github.com/Azure/app-service-announcements-discussions/issues/41

**Comment by cgillum** [comment]
The Durable Functions extension ([Microsoft.Azure.WebJobs.Extensions.DurableTask](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/)) has been updated to version **v1.2.1-beta3**, which is compatible with the new v2.0.11651-alpha functions runtime. I've updated the table above with this information. Release notes for this update can be found [here](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.2.1-beta3).

**Comment by davidebbo** [comment]
One more note: if you are stuck and need to get a v2 app back up and running asap, , you can set FUNCTIONS_EXTENSION_VERSION=2.0.11587-alpha in the App Settings to go back to previous build. But this is only a temporary measure, as the old build will later disappear and you should always be on the latest Preview. So while you do that, use a separate app to get ready for the new build, and then move all your apps back to `FUNCTIONS_EXTENSION_VERSION=beta`.

**Comment by mattchenderson** [comment]
I just updated the table for [Microsoft.Azure.WebJobs.Extensions.MicrosoftGraph](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.MicrosoftGraph/1.0.0-beta3).

CC @ConnorMcMahon

**Comment by davidebbo** [comment]
It took a little longer than we would have wanted, but the updated Azure Functions and WebJobs Tools VS extension is now up. Please go ahead and upgrade. The new version is 15.0.40405.0.

**Important**: At this point, there is no reason for anyone to still be running the older build. We will keep this old build around for a while longer to make sure everyone transitions. But please make sure you do this to avoid suddenly being broken when the old build is removed!
